title: "Camila Maldonado Franco"
author: "Camila Maldonado"
description: "Hi, you all! I am a sophomore at Smith College double majoring in Data Science and Education. I am an international student from Paraguay. I am trying to find my career path where I can mix both social sciences and data science. As one of my favorite professors says, I would like to show and not just tell why some things should matter to us. I am comfortable working with R and Python programming languages. I have experience visualizing data using Tableau and Datawrapper as well. I am hoping to showcase in this blog some of my work done in my free time as well as assignments from my data science courses. Outside of my academic journey, I enjoy biking around the Pioneer Valley, criticizing Netflix shows, and writing stories for children.

" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "camilamaldonado01.cm@gmail.com"
twitter_username: "camiluchipy"
github_username: "kamicazepy"
linkedin_username: "Camila Maldonado"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
